sonar.projectKey=aaiisyah_todoapp
sonar.organization=aaiisyah
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/TodoappApplication.java
sonar.language=java